#ifndef ENGINE_TETROMINO_TYPE_H
#define ENGINE_TETROMINO_TYPE_H

#define TETROMINO_TYPE_UNDEFINED 0
#define TETROMINO_TYPE_O 1
#define TETROMINO_TYPE_Z 2
#define TETROMINO_TYPE_S 3
#define TETROMINO_TYPE_L 4
#define TETROMINO_TYPE_J 5
#define TETROMINO_TYPE_I 6
#define TETROMINO_TYPE_T 7
#define TETROMINO_TYPE_COUNT 7

#endif
