#ifndef ENGINE_TETRIS_ACTION_H
#define ENGINE_TETRIS_ACTION_H

#define TETRIS_ACTION_MOVE_LEFT 0
#define TETRIS_ACTION_MOVE_RIGHT 1
#define TETRIS_ACTION_MOVE_DOWN 2
#define TETRIS_ACTION_ROTATE_LEFT 3
#define TETRIS_ACTION_ROTATE_RIGHT 4
#define TETRIS_ACTION_HARD_DROP 5
#define TETRIS_ACTION_HOLD 6
#define TETRIS_ACTION_TICK_DOWN 7

#endif
